services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend/Dockerfile.backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "backend"
    env_file:
      - ../../backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend/Dockerfile.frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge 